il_mode: CIL
dataset: fewrel_task8
classification_type: sentence-level
backbone_type: generative
backbone_extract_token: last_token
prompt_type: auto
method: HippoLite
classifier: None
classifier_lr: 1e-3
PEFT_type: None
is_replay: false
batch_size: 8
lr: 2e-5
weight_decay: 5e-4
training_epochs: 3
hippo_gradckpt: true
hippo_widthref: 2560
hippo_orthobasis: true
