il_mode: CIL
dataset: banking77_task7
classification_type: sentence-level
backbone_type: generative
backbone_extract_token: last_token
prompt_type: auto
method: SculptSVD
classifier: None
classifier_lr: 1e-3
PEFT_type: None
is_replay: false
batch_size: 8
lr: 2e-5
weight_decay: 5e-4
training_epochs: 3
pdr_no_liger: true
sculpt_rank: fixed
