il_mode: CIL
dataset: clinc150_task15
classification_type: sentence-level
backbone_type: discriminative
backbone_extract_token: cls_token
prompt_type: auto
method: HippoLiteEnc
classifier: Linear
classifier_lr: 1e-3
PEFT_type: None
is_replay: false
batch_size: 8
lr: 2e-5
weight_decay: 5e-4
training_epochs: 3
hle_fresh: true
hle_tabstep: true
hle_uniform: true
hle_gdown: true
hle_sleepdrop: true
hle_cmpall: true
hle_owm: false
hle_owmg: false
hle_tabowm: true
hle_pdet: true
hle_js0: true
hle_oldrow: true
hle_wdfold: true
hle_sink: true
hle_cmpowm: true
hle_tabln: true
